### ISSUE TITLE
User can view a list of movies on home page #1

### ISSUE THREAD

**Issue by techmatlock** [techmatlock/moviepod#1]
## ⚙️ Feature

User can view a list of movies on home page.

## 📐 Functionality

Allow users to view a list of movies.  And scroll down to see additional movies added.

## 🖼️ Wireframes

![Screenshot 2024-06-18 at 10 10 07 AM](https://github.com/techmatlock/front-end-project/assets/2618095/688d7ec6-e359-4905-856e-7b701da829dc)         ![Screenshot 2024-06-18 at 10 10 22 AM](https://github.com/techmatlock/front-end-project/assets/2618095/ab57df4e-78b4-44c8-9d50-bd802996c7c6)

![Screenshot 2024-06-18 at 10 07 31 AM](https://github.com/techmatlock/front-end-project/assets/2618095/a3f7b2c6-0e50-4aa2-b957-b20d0b2191fa)

## ✅ Task List
- [x] Complete HTML for header and navigation bar.
  - [x] Write CSS for mobile devices first.
  - [x] Adjust styling to fluidly adapt to desktop.
- [x] Complete HTML for the body which includes a: title and four column card wrapper.
  - [x] Use flexbox to use a flex basis of 25% for each item (4 column), space between, gap, wrap content, and align center.
- [x] In `index.html`:
  - [x] Create two data-views attributes. One for home page and one for learn more page.
  - [x] Make sure the card wrapper includes an image element, anchor element, and a content box.
  - [x] Add CSS to show hover animation on cards.
- [x] In `main.ts`, create an async function using the fetch method to get data from the API.
  - [x] Check to see if data exists, if not return.
  - [x] If data exists, convert the data to JSON.
- [x] In `main.ts`, create a render function to accept json data and render to page.
  - [x] You will need to have dummy data in `index.html` to:
  - [x] See what elements, attributes, and classes need to be added to the DOM.
  - [x] Delete dummy data from `index.html`after render function is working.
- [x] In `data.ts`, create an Interface for the data with properties:
  - [x] data-view (type string), imgUrl (type string), title (type string), summary (type string), releaseDate (type string), votes (type number), rating (type number), genre (type number array).
  - [x] Initialize data object (type Data) with 'home' assigned to data-view attribute.  All other properties should be null.
pre-existing data model.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
