### ISSUE TITLE
User can infinite scroll

### ISSUE THREAD

**Issue by techmatlock** [techmatlock/moviepod#12]
## ⚙️ Feature

User can infinite scroll.

## 📐 Functionality

If the user reaches the end of the page, more movies are added to the site.

## ✅ Task List

- [ ] Create global variables at top of `main.ts`:
  - [ ] apiUrl, perPage, and page = 1 for the initial page. 
    - [ ] In your fetch data, async function, create a template literal for the `fetch` argument.
- [ ] In your `getMovies` async function:
  - [ ] After the first call, increase the `page` global variable by 1. 
- [ ] Create an intersection observer with:
  - [ ] a `querySelector` to get the target element for an element at the bottom of the container.
  - [ ] a `callback function` and `options` argument. 
    - [ ] The options argument should have:
      - [ ] `root` property should equal `null`.
      - [ ] `threshold` property should equal 0.80 or 80%.
    - [ ] Use your `getMovies` async function with the parameters `entries` and `observer.
      - [ ] Call the `forEach` method on your `entries` array.
        - [ ] Call the element being iterated on `entry`.
        - [ ] Use a conditional to check if `entry.isIntersecting`
        - [ ] If true, call the `async` function `loadMoreMovies`
   - [ ] Call the `observe` method on your `observer` object you just created and pass in the target element `$row`.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by techmatlock** [comment]
![Recording2024-06-27at15 45 37-ezgif com-optimize](https://github.com/techmatlock/front-end-project/assets/2618095/9bd19def-095d-4fc5-bceb-94b9123ce75b)
