### ISSUE TITLE
User can view details of a movie on learn more page #2

### ISSUE THREAD

**Issue by techmatlock** [techmatlock/moviepod#3]
## ⚙️ Feature

If a user wants to view more details about a movie, they can click on the learn more button which will redirect them to the learn more page.

## 📐 Functionality

User can view details of a movie on learn more page

## 🖼️ Wireframes

<img width="736" alt="Screenshot 2024-06-20 at 11 39 47 AM" src="https://github.com/techmatlock/front-end-project/assets/2618095/02652450-492d-4dd4-a247-25cbcf79dd97">
<img width="192" alt="Screenshot 2024-06-20 at 11 39 58 AM" src="https://github.com/techmatlock/front-end-project/assets/2618095/69b71215-ee27-422a-b95c-9aaef3bbe156">

## ✅ Task List
- [ ] Create dummy data for learn more page:
- [ ] Create `renderMovieDetails` function to:
  - [ ] mimic dummy data with correct elements and attribute values.
  - [ ] once working, delete the dummy data.
- [ ] Create a viewSwap function
  - [ ] Use `querySelectorAll` method to get all elements with `data-view` attribute.
  - [ ] Use a `forEach` loop to find data-view that matches `learn-more`.
  - [ ] Remove `hidden` class from matching element and add `hidden` to non-matching elements.
- [ ] Add `click` event listener to the `movie-row` container.
  - [ ] Add a guard clause if event target doesn't match `a` element, exit event listener immediately.
  - [ ] Use the `closest` method to find the nearest card element.
  - [ ] Use a loop to find matching card.id that was clicked on and the array of movie objects` id.
    - [ ] Call the viewSwap function to pass the string `learn-more` as an argument.
    - [ ] Pass each card object to `renderMovieDetails`.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
