### ISSUE TITLE
User can save a movie to their favorites list #4

### ISSUE THREAD

**Issue by techmatlock** [techmatlock/moviepod#4]
## ⚙️ Feature

User can save a movie to their favorites list.

## 📐 Functionality

A user can save a movie to their favorites list by clicking on the heart located on each movie.

## 🖼️ Wireframes

![Screenshot 2024-06-24 at 4 41 41 PM](https://github.com/techmatlock/front-end-project/assets/2618095/35a77281-c297-4119-9017-3611d3c0588d)
![Screenshot 2024-06-24 at 4 41 20 PM](https://github.com/techmatlock/front-end-project/assets/2618095/5ecfdf1f-34e7-4e65-b251-8bf31e7f8796)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Save data to `localStorage`
  - [x] In `data.ts`:
    - [x] Create a `beforeunload` event listener:
      - [x] use `stringify` to convert the data object to JSON.
    - [x] Saved the JSON data to a variable using `getItem` to fetch previous JSON data.
        - [x] if there is no previous JSON data, then `stringify` jSON data and use `setItem` method to save to local storage.
     - [x] Create a conditional to check:
       - [x] if there's previous json data, then parse the previous saved JSON data.
- [x] In `data.ts`:
  - [x] Add a `favorites` property to the Movie interface of type `boolean`
  - [x] Add a `favorites` property to the Data interface of type `Movie[]`
- [ ] In `main.ts`:
  - [ ]  add font-awesome heart icons on `renderCard` function and place them on top of each card's movie poster.
  - [ ]  add heart icon to details view in `index.html`.
  - [ ] Create an `id` attribute for the icons to identify which one is clicked later.
- [ ] Add click event listener to heart and:
  - [ ] Use a conditional to check if the heart icon is already solid.
  - [ ] Change heart class using `classList` method to change heart to solid color.
  - [ ] Loop through movies array to find matching card based on id and push object to favorites list.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
