### ISSUE TITLE
User can remove a movie from their favorites #5

### ISSUE THREAD

**Issue by techmatlock** [techmatlock/moviepod#5]
## ⚙️ Feature

User can remove a movie from their favorites.

## 📐 Functionality

If a user clicks on a already favorited movie, the heart will change to an unfavorited state.

## 🖼️ Wireframes

![Recording 2024-06-26 at 10 59 31](https://github.com/techmatlock/front-end-project/assets/2618095/24bb122e-078b-4f6e-a3e0-21ab30c983ba)

## ✅ Task List

- [ ] In the `click`event listener for heart icon:
  - [ ] Check if icon `classList` method already contains solid color. If so, change icon `className` to class without solid color.
    - [ ] Also loop through `data.favorites` array and check if icon id matches a object in the array. If so, use `splice` to remove stored favorite.
    - [ ] In your favorites `view`: 
      - [ ] validate the card icon that was clicked with the card's id.
      - [ ] remove element from DOM using `replaceChild` or `remove` method.
    - [ ] You will need to account for all three views: home, details, and favorites.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
