### ISSUE TITLE
User can view their favorite movies #3

### ISSUE THREAD

**Issue by techmatlock** [techmatlock/moviepod#6]
## ⚙️ Feature

User can view their favorite movies.

## 📐 Functionality

The user can favorite or remove their movie by clicking the heart on each movie.

## 🖼️ Wireframes

![Screenshot 2024-06-24 at 8 36 56 AM](https://github.com/techmatlock/front-end-project/assets/2618095/d8edac4c-6161-42ec-af4f-c5c3ffe719b3)
![Screenshot 2024-06-24 at 8 37 39 AM](https://github.com/techmatlock/front-end-project/assets/2618095/a4e5fcaf-c503-427b-b88c-b362fd1301e1)

## ✅ Task List

- [ ] Create HTML & CSS for sidebar
  - [ ] Add a parent sidebar div above the main `container`.
    - [ ] Sidebar should have a `position`: fixed, `background-color`: white, `height`: 100%, `width`: 150px `z-index`: 1, `transition`: width 0.3s. linear
    - [ ] Add a `hidden` class to the sidebar (to remove later when user clicks on the toggle button).
  - [ ] Add a child sidebar header div.
    - [ ] `width`: 100%, `height`: 50px, `display`: flex, `justify-content`: center, `align-items`: center
  - [ ] Add a child sidebar menu div.
    - [ ] Add `a` element with a class `sidebar-item`
    - [ ] Add one child `div` element with class `sidebar-icon`
    - [ ] Add a h4 element for title.
- [ ] Add `click` event listener to menu toggle icon:
    - [ ] Use `classList` method to toggle parent sidebar to add or remove hidden class.
- [ ] Add `click` event listener for sidebar menu:
  - [ ] If user clicks home:
    - [ ] toggle sidebar menu to close.
    - [ ] then call `viewSwap` function and pass the `home` view as an argument.
   - [ ] If user clicks favorites:
       - [ ] toggle sidebar menu to close.
       - [ ] then call `viewSwap` function and pass `favorites` view as an argument.
- [ ] Add reset function for the view so that when a user clicks on a new movie it doesn't show the old on until it renders the change
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
